# Generated by Django 4.1.4 on 2024-01-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="users_profile_logos/"
            ),
        ),
    ]
