# Generated by Django 4.1.4 on 2024-01-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_alter_profile_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
