# Generated by Django 4.1.4 on 2024-02-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0004_profile_created_date_profile_updated_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="currency",
        ),
    ]
