apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automagic-app-media-pvc
  namespace: automagic-developer
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  storageClassName: nfs
